import React from 'react';
import { Button } from 'antd';
import { connect } from 'react-redux';



class Class extends React.Component {
  
  render() {
    const {article} = this.props;
    return(
      <div style={{ padding: 24, background: '#fff', textAlign: 'left' }}>

        <h3>分类</h3>
        <br/>
        <p>目前共计3个分类</p>
        <br/>
        <br/>
        ...
        <br />
        ...
        <br />
        ...
        <br />
        long
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        content
      </div>

    )
  }
}

const mapStatetoProps = (state) => {
  return {
    article: state.homeData
  }
}
  
  
export default connect(mapStatetoProps, null)(Class);