import React from 'react';
import { Button } from 'antd';
import { connect } from 'react-redux';



class Post extends React.Component {
  
  render() {
    const {article} = this.props;
    return(
          <div style={{ padding: 24, background: '#fff', textAlign: 'left' }}>

          <h3>| {article[0].title}</h3>
          <p style={{fontWeight: "lighter"}}>发表于 {article[0].time} 分类于 {article[0].category}</p>
          <p>{article[0].content}</p>
          <br/>
          <br/>
          <br/>
          ...
          <br />
          ...
          <br />
          ...
          <br />
          long
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          content
        </div>

    )
  }
}

const mapStatetoProps = (state) => {
    return {
      article: state.homeData
    }
  }
  
  
  export default connect(mapStatetoProps, null)(Post);